/**
 * `fh-toolkit burn <host>`: burn-in for an EMPTY Proxmox host, before it carries nodes.
 *
 * Like host-check, the verb prints a bash script for the operator to run ON the host
 * (`fh-toolkit burn pve25 | ssh root@pve25 bash`), filled in with the host's planned node
 * VMs from the inventory. The script fetches the fh-burner release this toolkit pins (a VM
 * image and the host controller, burner/ in this repo, each with a .sha256) and hands the
 * plan to the controller, which clones one burn VM per planned node and ramps them 1..N:
 * each new VM fills its memory while every VM writes to disk, then all run a CPU and a disk
 * test at the same moment, while the host is sampled. The verdict is the HOST's — free
 * memory, swap, memory pressure, stalls, OOM kills — FAIL / WARN / OK; burner/README.md has
 * the rules. By default each VM uses all its memory, and a FAIL there re-runs at 90%, so
 * the report says how far past the edge the host is.
 *
 * Why it exists (pve25, 09-27): one nimbus at 31744 MB on 32 GB, all its memory used while
 * the disk was busy, stalled the host 12 s even with zram + swap + KSM on, and was
 * OOM-killed with them off; at 90% it was a WARN. host-check does the arithmetic; burn is
 * the host actually carrying the load.
 *
 * The script refuses a host where any of its node VMs already exists: burn VMs would
 * compete with live nodes and fail their benchmarks. Other VMs (a gateway) are fine —
 * they will be there under the real nodes too — and are listed.
 */
import type { HostCheckInput } from "./host-check";
import { TIER_VM_SIZES } from "./proxmox-probe";
import { TIER_DEFAULT_MB } from "./vm-memory";

/** The fh-burner release this toolkit runs (burner/VERSION when it was cut). */
export const BURNER_VERSION = "0.2.3";
export const BURNER_RELEASES = "https://github.com/w2vy/moltentech-operator/releases/download";

export interface BurnVm {
  tier: string;
  mb: number;
  cores: number;
  pool: string;
}

export interface BurnOptions {
  /** Burn these instead of the inventory's slots: `[{ tier: "nimbus", count: 1 }]`. */
  plan?: { tier: string; count: number }[];
  /** `max` (default: all of each VM's memory) or a percent. */
  fill?: string;
  /** Leave the burn VMs running at the end. */
  keep?: boolean;
  /** Do not re-run at 90% when a full fill FAILs. */
  noRetry?: boolean;
}

const shq = (s: string) => `'${s.replace(/'/g, `'\\''`)}'`;
const coresOf = (tier: string) => TIER_VM_SIZES.find((t) => t.tier === tier)?.cores;

/** One burn VM per planned node: the host's size for its tier, the tier's cores, the slot's pool. */
export function burnVms(host: HostCheckInput, plan?: BurnOptions["plan"]): BurnVm[] {
  const mbOf = (tier: string) => host.vmMemoryMb?.[tier] ?? TIER_DEFAULT_MB[tier]!;
  const slots = plan
    ? plan.flatMap((p) => Array.from({ length: p.count }, () => ({ tier: p.tier, storagePool: undefined })))
    : host.slots;
  return slots
    .filter((s) => TIER_DEFAULT_MB[s.tier] !== undefined && coresOf(s.tier) !== undefined)
    .map((s) => ({ tier: s.tier, mb: mbOf(s.tier), cores: coresOf(s.tier)!, pool: s.storagePool || host.storageImages }));
}

/** `nimbus:1,cumulus:2` → plan; undefined with a reason when it does not parse. */
export function parseBurnPlan(text: string): { plan?: BurnOptions["plan"]; error?: string } {
  const plan: { tier: string; count: number }[] = [];
  for (const part of text.split(",").filter(Boolean)) {
    const m = /^([a-z]+)(?::(\d+))?$/.exec(part.trim());
    if (!m || TIER_DEFAULT_MB[m[1]!] === undefined) return { error: `'${part}' — want <tier>[:<count>], tier one of ${Object.keys(TIER_DEFAULT_MB).join(", ")}` };
    const count = m[2] === undefined ? 1 : Number(m[2]);
    if (count < 1 || count > 64) return { error: `'${part}' — count 1..64` };
    plan.push({ tier: m[1]!, count });
  }
  return plan.length ? { plan } : { error: "empty plan" };
}

export function burnScript(host: HostCheckInput, toolkitVersion: string, opts: BurnOptions = {}): string {
  const vms = burnVms(host, opts.plan);
  const plan = vms.map((v) => `${v.tier}:${v.mb}:${v.cores}:${v.pool}`).join(" ");
  const names = host.slots.map((s) => s.vmName).filter((n): n is string => !!n);
  const fill = opts.fill ?? "max";
  const args = [`--fill ${shq(fill)}`, opts.keep ? "--keep" : "", opts.noRetry ? "--no-retry" : ""].filter(Boolean).join(" ");
  // ~3 min a step: boot, fill + 8 GB writes, settle, 30 s CPU, 2 GB writes.
  const minutes = Math.max(3, vms.length * 3);
  const retry = fill === "max" && !opts.noRetry;
  return `#!/bin/bash
# fh-toolkit burn ${host.name} — generated by fh-toolkit ${toolkitVersion}. Run ON the host as root:
#   fh-toolkit burn ${host.name} | ssh root@${host.name} bash
# Creates burn VMs (template 9900, 9901+, tag fh-burn, no network); at the end removes them, the
# template and the download (all but the results in /var/tmp/fh-burn) unless --keep.
# Everything runs inside main(), with stdin from /dev/null, so nothing it runs can read the
# rest of this script off the ssh pipe.
set -uo pipefail
main() {
HOST=${shq(host.name)}
V=${shq(BURNER_VERSION)}
URL=${shq(BURNER_RELEASES)}/fh-burner-v$V
D=\${FH_BURN_DIR:-/var/lib/vz/fh-burn}
PLAN=${shq(plan)}
NODE_NAMES=${shq(names.join(" "))}

[ "$(id -u)" = 0 ] || { echo "burn: run as root on the Proxmox host"; return 1; }
command -v qm >/dev/null || { echo "burn: no qm here — run this ON the Proxmox host"; return 1; }
[ -n "$PLAN" ] || { echo "burn: $HOST has no node slots in the inventory — say what to burn: fh-toolkit burn $HOST --plan nimbus:1"; return 1; }
here=$(hostname -s)
[ "$here" = "$HOST" ] || echo "burn: note — this plan is for $HOST, and this host calls itself $here"

# An EMPTY host: burn VMs next to live nodes would fail their benchmarks.
live=""; other=""
while read -r id name status _; do
  case $name in fh-burn-*|fh-burner-tmpl) continue ;; esac
  node=0
  for n in $NODE_NAMES; do [ "\${name#fh-}" = "\${n#fh-}" ] && node=1; done
  if [ $node = 1 ]; then live="$live $name($status)"; elif [ "$status" = running ]; then other="$other $name"; fi
done < <(qm list | tail -n +2)
if [ -n "$live" ]; then
  echo "burn: $HOST is not empty — these node VMs exist:$live"
  echo "      Burn a host before its nodes are built, or move them off first."
  return 1
fi
[ -n "$other" ] && echo "burn: also running (they stay on, as they will under the real nodes):$other"

mkdir -p "$D" && cd "$D" || return 1
for f in "fh-burner-$V.qcow2" "fh-burner-$V-host.sh"; do
  [ -f "$f" ] && [ -f "$f.sha256" ] && sha256sum -c --quiet "$f.sha256" >/dev/null 2>&1 && continue
  echo "burn: fetching $f"
  if ! wget -q -O "$f.sha256" "$URL/$f.sha256" || ! wget -q -O "$f" "$URL/$f"; then
    rm -f "$f" "$f.sha256"
    echo "burn: could not download $URL/$f — is fh-burner $V released?"; return 1
  fi
  sha256sum -c --quiet "$f.sha256" || { echo "burn: $f does not match its .sha256"; return 1; }
done

echo "burn: $HOST — $(echo "$PLAN" | wc -w) VM(s): $PLAN"
echo "burn: about ${minutes} min${retry ? ` (up to ${minutes * 2} if all-memory FAILs and it re-runs at 90%)` : ""}. Ctrl-C stops it and removes the burn VMs."
${opts.keep ? "" : `# A host that passes gets its nodes next, so nothing of burn's stays behind: the controller
# destroys the burn VMs, this removes the template and the download. bash runs a trap only once
# the controller has exited, so the VMs cloned from 9900 are gone first even on Ctrl-C.
trap 'tidy; exit 1' INT TERM HUP
`}bash "$D/fh-burner-$V-host.sh" --image "$D/fh-burner-$V.qcow2" --plan "$PLAN" ${args}
rc=$?
${opts.keep ? `echo "burn: --keep: template 9900 and $D left in place"` : "tidy"}
return $rc
}
tidy() {
  trap '' PIPE   # the ssh session may be gone; cleaning up must not die writing to it
  qm config 9900 2>/dev/null | grep -q '^tags:.*fh-burn' && qm destroy 9900 --purge 1 >/dev/null 2>&1
  # Only what this script fetched — FH_BURN_DIR may point somewhere shared.
  (cd "$D" 2>/dev/null && rm -f fh-burner-*.qcow2 fh-burner-*.qcow2.sha256 fh-burner-*-host.sh fh-burner-*-host.sh.sha256)
  rmdir "$D" 2>/dev/null
  echo "burn: removed template 9900 and the fh-burner download"
}
main < /dev/null
exit $?
`;
}
